// cadpessoas_ang/src/app/pessoa-editar/pessoa-editar.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-pessoa-editar',
  templateUrl: './pessoa-editar.component.html',
  styleUrls: ['./pessoa-editar.component.css']
})
export class PessoaEditarComponent implements OnInit {
  pessoa = {
    id: 0,
    nome: '',
    endereco: '',
    email: '',
    contato: ''
  };
  apiUrl = 'http://localhost:8080/pessoas';
  constructor(private http: HttpClient, private router: Router, private route: ActivatedRoute) { }
  ngOnInit(): void {
    this.getPessoa();
  }

  getPessoa():void {
    const id = this.route.snapshot.paramMap.get('id');
    this.http.get(`${this.apiUrl}/${id}`).subscribe(
      data => {
        this.pessoa = data as any;
      }, error => {
        console.log(error);
      }
    );
  }

  onSubmit(): void {
    this.http.put(`${this.apiUrl}`, this.pessoa).subscribe(
      response => {
        this.router.navigate(['/pessoa']);
      },
      error => console.log(error)
    );
  }

  voltar(): void {
    this.router.navigate(['/pessoa']);
  }

}

<h1>Editar pessoa</h1>>
<form (submit)="onSubmit()">
  <input [(ngModel)]="pessoa.nome" name="nome" placeholder="Nome"><br>
  <input [(ngModel)]="pessoa.endereco" name="endereco" placeholder="Endereco"><br>
  <input [(ngModel)]="pessoa.email" name="email" placeholder="E-mail"><br>
  <input [(ngModel)]="pessoa.contato" name="contato" placeholder="Contato"><br>
  <button type="submit">Atualizar</button><br><br>
</form>
<button (click)="voltar()">Voltar</button>

// cadpessoas_vue/src/components/PessoaEditar.vue
<template>
    <div>
        <h1>Editar pessoa</h1>
        <form @submit.prevent="onSubmit">
            <input v-model="pessoa.nome" placeholder="Nome" /><br>
            <input v-model="pessoa.endereco" placeholder="Endereço" /><br>
            <input v-model="pessoa.email" placeholder="E-mail" /><br>
            <input v-model="pessoa.contato" placeholder="Contato" /><br>
            <button type="submit">Atualizar</button>
        </form>
    </div>
</template>
<script>
import axios from 'axios';  

export default {
    data(){
        return {
            pessoa: {
                id: 0,
                nome: '',
                endereco: '',
                email: '',
                contato: ''
            }
        };
    },
    mounted(){
       const id = this.$route.params.id;
       axios.get(`http://localhost:8080/pessoas/${id}`)
            .then(response => {
                this.pessoa = response.data;
            })
            .catch(error => {
                console.log(error);
            });
    },
    methods:{
        onSubmit() {
            axios.put(`http://localhost:8080/pessoas`, this.pessoa)
                .then(response => {
                    this.$router.push('/pessoa');
                })
                .catch(error => {
                    console.log(error);
                });
        }
    }
}
</script>
