// cadpessoas_ang/src/app/pessoa-novo/pessoa-novo.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';

@Component({
  selector: 'app-pessoa-novo',
  templateUrl: './pessoa-novo.component.html',
  styleUrls: ['./pessoa-novo.component.css']
})
export class PessoaNovoComponent implements OnInit {

  ngOnInit(): void {

  }

  pessoa = {
    nome: '',
    endereco: '',
    email: '',
    contato: ''
  };

  apiURL = 'http://localhost:8080/pessoas';

  constructor(private http: HttpClient, private router: Router) { }

  onSubmit(): void {
    this.http.post(this.apiURL, this.pessoa).subscribe(
      response => {
        this.router.navigate(['/pessoa']);
      },
      error => console.log(error)
    );
  }

  voltar(): void {
    this.router.navigate(['/pessoa']);
  }
}

<h1>Nova pessoa</h1>
<form (submit)="onSubmit()">
  <input [(ngModel)]="pessoa.nome" name="nome" placeholder="Nome"><br>
  <input [(ngModel)]="pessoa.endereco" name="endereco" placeholder="Endereco"><br>
  <input [(ngModel)]="pessoa.email" name="email" placeholder="E-mail"><br>
  <input [(ngModel)]="pessoa.contato" name="contato" placeholder="Contato"><br>
  <button type="submit">Gravar</button><br><br>
</form>
<button (click)="voltar()">Voltar</button>

// cadpessoas_vue/src/components/PessoaNovo.vue
<template>
    <div>
        <h1>Nova pessoa</h1>
        <form @submit.prevent="onSubmit">
            <input v-model="pessoa.nome" placeholder="Nome" /><br>
            <input v-model="pessoa.endereco" placeholder="Endereço" /><br>
            <input v-model="pessoa.email" placeholder="E-mail" /><br>
            <input v-model="pessoa.contato" placeholder="Contato" /><br>
            <button type="submit">Gravar</button>
        </form>
    </div>
</template>
<script>
import axios from 'axios';  

export default {
    data(){
        return {
            pessoa: {
                nome: '',
                endereco: '',
                email: '',
                contato: ''
            }
        };
    },
    methods:{
        onSubmit() {
            axios.post(`http://localhost:8080/pessoas`, this.pessoa)
                .then(response => {
                    this.$router.push('/pessoa');
                })
                .catch(error => {
                    console.log(error);
                });
        }
    }
}
</script>
