// cadpessoas_vue/src/components/Pessoa.vue
<template>
    <div>
        <h1>Pessoas</h1>
    </div>
    <div>
        <router-link to="/pessoa/novo">Nova pessoa</router-link>
        <ul>
            <li v-for="pessoa in pessoas" :key="pessoa.id">
                {{ pessoa.nome }} - {{ pessoa.email }} &nbsp;
                <router-link :to="`/pessoa/editar/${pessoa.id}`">Editar</router-link>
                <button @click="excluirPessoa(pessoa.id)">Excluir</button>
            </li>
        </ul>
    </div>
</template>
<script>
import axios from 'axios';

export default {    
    data(){
        return {
            pessoas: []
        };
    },
    mounted(){
        axios.get('http://localhost:8080/pessoas')
            .then(response => {
                this.pessoas = response.data;
            })
            .catch(error => {
                console.log(error);
            });
    },
    methods: {
        excluirPessoa(id){
            if(!confirm('Deseja excluir esta pessoa?')){
                return;
            }
            axios.delete(`http://localhost:8080/pessoas/${id}`)
                .then(response => {
                    this.pessoas = this.pessoas.filter(pessoa => pessoa.id !== id);
                })
                .catch(error => {
                    console.log(error);
                });
        }
    }
}
</script>
<style scoped>
    /* estilos aqui*/
</style>

// cadpessoas_ang/src/app/pessoa/pessoa.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';

@Component({
  selector: 'app-pessoa',
  templateUrl: './pessoa.component.html',
  styleUrls: ['./pessoa.component.css']
})
export class PessoaComponent implements OnInit {

  pessoas: any[]=[];

  constructor(private http: HttpClient, private router: Router) { }


  ngOnInit(): void {
    this.http.get('http://localhost:8080/pessoas').subscribe(
      data => {
        this.pessoas = data as any[];
      }
    );
  }

  editarPessoa(id: number): void {
    //navegar para a página de edição de pessoa:
    this.router.navigate([`/pessoa/editar/${id}`]);
  }

  excluirPessoa(id: number): void {
    if(!confirm('Deseja realmente excluir esta pessoa?'))
      return;
    this.http.delete(`http://localhost:8080/pessoas/${id}`).subscribe(() => {
      this.pessoas = this.pessoas.filter(pessoa => pessoa.id !== id);
    });
  }

  novaPessoa(): void {
    this.router.navigate([`/pessoa/novo`]);
  }

}

<h1>Pessoas</h1>
<hr>
<ul>
  <li *ngFor="let pessoa of pessoas">
    {{ pessoa.nome }} - {{ pessoa.email }}
    <button (click)="editarPessoa(pessoa.id)">Editar</button> &nbsp;
    <button (click)="excluirPessoa(pessoa.id)">Excluir</button>
  </li>
</ul>
<button (click)="novaPessoa()">Nova Pessoa</button>
